name: Issue Notifier

on:
  issues:
    types:
      - opened

jobs:
  issue-info:
    if: contains(github.event.issue.labels.*.name, 'ChatGPT')
    runs-on: ubuntu-latest

    steps:
      - name: Print Issue Details
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Description: ${{ github.event.issue.body }}"
          echo "Issue Creator: ${{ github.event.issue.user.login }}"
