name: Issue to PR Workflow

on:
  issues:
    types:
      - opened

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: contains(github.event.issue.labels.*.name, 'ChatGPT')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Dummy File
        run: |
          echo "This is a dummy file created for issue #${{ github.event.issue.number }}" > dummy.txt

      - name: Create and Switch to New Branch
        run: |
          BRANCH_NAME="issue-${{ github.event.issue.number }}"
          git checkout -b $BRANCH_NAME
          git add dummy.txt
          git commit -m "Add dummy file for issue #${{ github.event.issue.number }}"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git $BRANCH_NAME

      - name: Create Pull Request
        id: create_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const issueNumber = ${{ github.event.issue.number }};
            const prTitle = `Resolve issue #${issueNumber}`;
            const prBody = `This PR resolves issue #${issueNumber}.\n\nresolves #${issueNumber}`;
            const response = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: prTitle,
              head: `issue-${issueNumber}`,
              base: 'main',
              body: prBody
            });
            console.log(`PR created: ${response.data.html_url}`);
            return response.data.number;

      - name: Request Reviewer
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const prNumber = ${{ steps.create_pr.outputs.result }};
            const creator = '${{ github.event.issue.user.login }}';
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              reviewers: [creator]
            });
            console.log(`Reviewer requested: ${creator}`);
