name: Regenerate Image Workflow

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write

jobs:
  regenerate-image:
    if: startsWith(github.event.comment.body, 'regenerate image')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract Content Type and Handle from PR Head Ref (with Fallback)
        run: |
          BRANCH_NAME="${{ github.event.issue.pull_request.head.ref || github.event.pull_request.head.ref }}"
          echo "Branch name detected: $BRANCH_NAME"

          if [[ -z "$BRANCH_NAME" ]]; then
            echo "Error: BRANCH_NAME is empty. Exiting."
            exit 1
          fi

          CONTENT_TYPE=$(echo "$BRANCH_NAME" | awk -F'/' '{print $3}')
          CONTENT_HANDLE=$(echo "$BRANCH_NAME" | awk -F'/' '{print $4}')

          echo "CONTENT_TYPE=$CONTENT_TYPE" >> $GITHUB_ENV
          echo "CONTENT_HANDLE=$CONTENT_HANDLE" >> $GITHUB_ENV

          echo "Extracted Content Type: $CONTENT_TYPE"
          echo "Extracted Content Handle: $CONTENT_HANDLE"

      - name: Install Dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Run Regenerate Image Script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Running yarn regenerateImage with content type: $CONTENT_TYPE and handle: $CONTENT_HANDLE"
          yarn regenerateImage "$CONTENT_TYPE" "$CONTENT_HANDLE"

      - name: Comment on Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = ${{ github.event.issue.number }};
            const contentType = process.env.CONTENT_TYPE;
            const contentHandle = process.env.CONTENT_HANDLE;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `✅ Image regenerated for content type: **${contentType}** with handle: **${contentHandle}**.`
            });
