name: Set Image Workflow

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  set-image:
    if: startsWith(github.event.comment.body, 'set image ')
    runs-on: ubuntu-latest

    steps:
      - name: Extract Image URL from Comment
        run: |
          IMAGE_URL=$(echo "${{ github.event.comment.body }}" | sed -n 's/^set image \(.*\)$/\1/p')
          echo "IMAGE_URL=$IMAGE_URL" >> $GITHUB_ENV
          echo "Extracted Image URL: $IMAGE_URL"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get PR details via GitHub API
        id: pr_details
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Branch Name and Checkout
        run: |
          BRANCH_NAME="${{ fromJson(steps.pr_details.outputs.data).head.ref }}"
          echo "Branch name detected: $BRANCH_NAME"

          if [[ -z "$BRANCH_NAME" ]]; then
            echo "Error: BRANCH_NAME is empty. Exiting."
            exit 1
          fi

          git fetch origin "$BRANCH_NAME"
          git checkout "$BRANCH_NAME"

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Set Image Script
        run: |
          echo "Running yarn setImage with URL: $IMAGE_URL"
          yarn setImage "$IMAGE_URL"

      - name: Commit & Push Changes
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Re-generate image for $CONTENT_TYPE/$CONTENT_HANDLE"
            git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git "$CURRENT_BRANCH"
          else
            echo "No changes to commit."
          fi


      - name: Comment on PR with Image URL
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.issue.number }};
            const imageUrl = process.env.IMAGE_URL;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `✅ Image updated to: [${imageUrl}](${imageUrl})`
            });